import { fetchFiles } from "./TeamImages";
let filesPromise = fetchFiles();

filesPromise.then(files => {
  domainLeadsData = [
    {
      id: 1,
      img: `${files[2].url}`,
      name: "Pooranjoy Bhattacharya",
      domain: "Web Development",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 2,
      img: `${files[0].url}`,
      name: "Cloud Computing",
      domain: "Abhijnyan Das",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 3,
      img: `${files[25].url}`,
      name: "Madhurjya Dasgupta",
      domain: "Cybersecurity",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 4,
      img: `${files[26].url}`,
      name: "Rishav Krishnan",
      domain: "App Development",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 5,
      img: `${files[23].url}`,
      name: "Shivam Sourav",
      domain: "AI/ML",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 6,
      img: `${files[28].url}`,
      name: "Kuldeep Bora",
      domain: "UI/UX Design",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 7,
      img: `${files[5].url}`,
      name: "Dhruv Bhutura",
      domain: "Public Relations",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
  ];

  CoreTeamData = [
    {
      id: 8,
      img: `${files[20].url}`,
      name: "Toshith Yadav",
      domain: "Web Development",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 9,
      img: `${files[13].url}`,
      name: "Seedorf Rai",
      domain: "Web Development",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 10,
      img: `${files[24].url}`,
      name: "Girish Sharma",
      domain: "Web Development",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 11,
      img: `${files[32].url}`,
      name: "Madhurya Hait",
      domain: "Web Development",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 12,
      img: `${files[9].url}`,
      name: "Sneha Supriya",
      domain: "AI/ML",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 13,
      img: `${files[4].url}`,
      name: "Om Gupta",
      domain: "AI/ML",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 14,
      img: `${files[1].url}`,
      name: "Mayur K T",
      domain: "AI/ML",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 15,
      img: `${files[19].url}`,
      name: "Pratham Srivastava",
      domain: "AI/ML",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 16,
      img: `${files[6].url}`,
      name: "Neha Sultan",
      domain: "AI/ML",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 17,
      img: `${files[33].url}`,
      name: "Indraneel Das",
      domain: "Cybersecurity",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 18,
      img: `${files[29].url}`,
      name: "Shayan Vatsa",
      domain: "Cybersecurity",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 19,
      img: `${files[17].url}`,
      name: "Gunjan Chakrabartty",
      domain: "Cybersecurity",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 20,
      img: `${files[12].url}`,
      name: "Ishaan S. Oshima",
      domain: "Cybersecurity",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 21,
      img: `${files[27].url}`,
      name: "Manaswi Jha",
      domain: "UI/UX Design",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 22,
      img: `${files[31].url}`,
      name: "Priyanjana Paul",
      domain: "UI/UX Design",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 23,
      img: `${files[3].url}`,
      name: "Sneha Seal",
      domain: "Cloud Computing",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 24,
      img: `${files[15].url}`,
      name: "Deepak Manda",
      domain: "Cloud Computing",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
    {
      id: 25,
      img: `${files[7].url}`,
      name: "Prantor J. Bharadwaj",
      domain: "Cloud Computing",
      twitter: "https://john",
      insta: "https://john",
      linkedin: "https://john",
    },
  ];

  leadImg = `${files[34].url}`;
});


export let domainLeadsData = [];
export let CoreTeamData = [];
export let leadImg = '';