export const domainLeadsData = [
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "John",
    domain: "Web Dev",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "Gon",
    domain: "Ai Ml",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "Mon",
    domain: "Cyber",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "Mon",
    domain: "Cyber",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "John",
    domain: "Web Dev",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "Gon",
    domain: "Ai Ml",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "Mon",
    domain: "Cyber",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
];

export const CoreTeamData = [
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "John",
    domain: "Web Dev",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "Gon",
    domain: "Ai Ml",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "Mon",
    domain: "Cyber",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "John",
    domain: "Web Dev",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "Gon",
    domain: "Ai Ml",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "Mon",
    domain: "Cyber",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "John",
    domain: "Web Dev",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "Gon",
    domain: "Ai Ml",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "Mon",
    domain: "Cyber",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "John",
    domain: "Web Dev",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "Gon",
    domain: "Ai Ml",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
  {
    img: "https://bootstrapious.com/i/snippets/sn-team/teacher-4.jpg",
    name: "Mon",
    domain: "Cyber",
    twitter: "https://john",
    insta: "https://john",
    linkedin: "https://john",
  },
];
