name: 'Greetings'

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Congratulations, @${{ github.actor }}! 🎉 Thank you for creating the issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!'
          pr-message: 'Great job, @${{ github.actor }}! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project. Keep being the part of the community!'
          footer: |
            'We will promptly review your changes and offer feedback. Keep up the excellent work! 
            Kindly remember to check our [Contributing Guidelines](https://github.com/gdscsmit/gdscsmit.github.io/blob/main/CONTRIBUTING.md)'
